# -*- coding: utf-8 -*-
"""Getting started with Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m_-SvfCCTzSuCv4jPo1_KhFpgS0gAyOP
"""

import matplotlib.pyplot as plt
import numpy as np

plt.plot([1,2,3,4])
plt.grid()
plt.xlabel('number-x-axis')
plt.ylabel('values-y-label')
plt.show()

t=np.arange(0.0,5.0,0.1)

plt.plot(t,t**2,'ro',label='**2')
plt.plot(t,t**2.2,'b--',label='**2.2')
plt.plot(t,t**2.5,'^g',label='**2.5')
plt.grid()
plt.legend()
plt.show()

x1=[1,2,3,4]
y1=[1,4,9,16]
x2=[1,2,3,4]
y2=[1,4,6,8]

lines = plt.plot(x1,y1,x2,y2)

plt.setp(lines[0],color='red',linewidth=2.5)

plt.setp(lines[1],color='blue',linewidth=4.0)
plt.grid()
#plt.show()

plt.figure(1)
plt.subplot(211)
plt.plot([1,2,3,4],'ro')
plt.grid()

colors=['red','blue','yellow','orange']
plt.subplot(212)
plt.hist([10,25,46,78],color='yellow')
plt.grid()

plt.show()

plt.figure(1)

plt.subplot(221)
plt.plot([1,4,3,12,8])
plt.grid()


plt.subplot(222)
t1=np.arange(0.0,0.5,0.1)
plt.plot(t1,'r*')
plt.grid()

plt.figure(2)
plt.subplot(111)
plt.bar([1,6,3,9,18,14],['x','y','a','b','c','d'])
plt.grid()


plt.figure(3)

plt.subplot(221)
plt.hist([10,43,25,66])

plt.subplot(222)
plt.pie([44,20,30,6])
plt.show()